dist: xenial
language: r
r:
  - oldrel
  - release
# see also https://docs.travis-ci.com/user/languages/r

# Using the package cache to store R package dependencies can significantly
# speed up build times and is recommended for most builds.
cache:
  - apt
  - packages
sudo: required
warnings_are_errors: false
services:
- docker
install:
- sudo add-apt-repository -y ppa:deadsnakes/ppa
- sudo apt-get update
- sudo apt-get install -y python3.6 curl unixodbc-dev
- curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6
- sudo pip install pipenv
- git clone https://github.com/exasol/integration-test-docker-environment.git
- Rscript -e 'install.packages("testthat")'
- Rscript -e 'install.packages("devtools")'
- Rscript -e 'install.packages("remotes")'
- Rscript -e 'library(remotes);install_version("RODBC","v1.3-16")'
- Rscript -e 'install.packages("assertthat")'
- Rscript -e 'devtools::install_github("jimhester/covr")'
- Rscript -e 'devtools::install_github("jimhester/lintr")'
- Rscript -e 'devtools::install_github("marcelboldt/DBI")'
- Rscript -e 'devtools::install_github("marcelboldt/DBItest")'
before_script:
  - pushd ./integration-test-docker-environment && bash -x start-test-env spawn-test-environment --environment-name test --database-port-forward 8888 --bucketfs-port-forward 6666 && popd
script:
  - Rscript -e 'devtools::install()'
  - pushd tests && R -f testthat.R && popd
after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'devtools::install(); lintr::lint_package()'

